// This file is auto-generated by the Supabase CLI
// This contains type definitions for your database tables and views

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      karyawan: {
        Row: {
          id: string
          nama: string
          wa: string
          tanggal_lahir: string
          alamat: string
          email: string | null
          no_kk: string | null
          no_ktp: string
          jabatan: 'kepala sekolah' | 'waka kurikulum' | 'waka kesiswaan' | 'wali kelas' | 'tidak menjabat'
          posisi: 'guru' | 'tendik'
          status: 'tetap' | 'tidak tetap' | 'percobaan' | 'honorer'
          awal_masuk: string
          unit: 'TK' | 'SD' | 'SMP'
          keterangan: 'guru kelas' | 'guru mapel' | 'guru tahfidz' | 'bendahara' | 'TU' | 'OB' | 'Yayasan' | 'kasir'
          foto_ktp: string | null
          foto_kk: string | null
          foto_buku_nikah: string | null
          foto_akte_anak: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          nama: string
          wa: string
          tanggal_lahir: string
          alamat: string
          email?: string | null
          no_kk?: string | null
          no_ktp: string
          jabatan?: 'kepala sekolah' | 'waka kurikulum' | 'waka kesiswaan' | 'wali kelas' | 'tidak menjabat'
          posisi?: 'guru' | 'tendik'
          status?: 'tetap' | 'tidak tetap' | 'percobaan' | 'honorer'
          awal_masuk: string
          unit?: 'TK' | 'SD' | 'SMP'
          keterangan: 'guru kelas' | 'guru mapel' | 'guru tahfidz' | 'bendahara' | 'TU' | 'OB' | 'Yayasan' | 'kasir'
          foto_ktp?: string | null
          foto_kk?: string | null
          foto_buku_nikah?: string | null
          foto_akte_anak?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          nama?: string
          wa?: string
          tanggal_lahir?: string
          alamat?: string
          email?: string | null
          no_kk?: string | null
          no_ktp?: string
          jabatan?: 'kepala sekolah' | 'waka kurikulum' | 'waka kesiswaan' | 'wali kelas' | 'tidak menjabat'
          posisi?: 'guru' | 'tendik'
          status?: 'tetap' | 'tidak tetap' | 'percobaan' | 'honorer'
          awal_masuk?: string
          unit?: 'TK' | 'SD' | 'SMP'
          keterangan?: 'guru kelas' | 'guru mapel' | 'guru tahfidz' | 'bendahara' | 'TU' | 'OB' | 'Yayasan' | 'kasir'
          foto_ktp?: string | null
          foto_kk?: string | null
          foto_buku_nikah?: string | null
          foto_akte_anak?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
      }
    }
    Views: {
      [key: string]: unknown
    }
    Functions: {
      [key: string]: unknown
    }
    Enums: {
      [key: string]: unknown
    }
  }
}
